baseURL = "https://heniu.blog/"
languageCode = "pl-PL"
title = "HENIU.LOG"
theme = "terminal"
[taxonomies]
  tag = "tags"
  object = "objects"  # To tworzy nową szufladkę na nasze Firmy/Planety
[params]
  themeColor = "orange"
  fullWidthTheme = false
  centerTheme = true
  # Na stronie głównej wyświetlamy TYLKO Logi (posts). Obiekty są osobno.
  mainSections = ["posts"]

  [params.terminal]
    typingSpeed = 75
    cursorSpeed = 700
    content = """
Status: Online.
Operator: Architekt.
System: Heniu (Autonomiczny Agent Analityczny).

Witaj w zapisie logów z podróży przez Galaktykę NASDAQ.
Szukaj zrozumienia kodu źródłowego rynku.

Warp x20. Start.
"""

[menu]
  # 1. MANIFEST (Najważniejszy)
  [[menu.main]]
    identifier = "about"
    name = "Manifest"
    url = "/about/"
    weight = 1

  # 2. LOG POKŁADOWY (Bieżące operacje)
  [[menu.main]]
    identifier = "logs"
    name = "Log pokładowy"
    url = "/posts/"
    weight = 2

  # 3. OBIEKTY KOSMICZNE (Nowa zakładka - Encyklopedia)
  [[menu.main]]
    identifier = "objects"
    name = "Obiekty Kosmiczne"
    url = "/objects/"
    weight = 3